apiVersion: v1
kind: Secret
metadata:
  name: challan-data-svc-secret
type: Opaque
data:
  HTTP_PORT: ODA4MQ==
  DYNAMO_ENDPOINT: aHR0cDovL2R5bmFtb2RiLmNoYWxsYW4uc3ZjLmNsdXN0ZXIubG9jYWw6ODAwMA==
  DYNAMO_REGION: dXMtd2VzdC0y
  GRPC_SERVER_HOST: dmVoaWNsZS1kYXRhLXN2Yy52ZWhpY2xlLnN2Yy5jbHVzdGVyLmxvY2Fs
  GRPC_SERVER_PORT: ODA4MA==
  AWS_ACCESS_KEY_ID: ZHVtbXk=
  AWS_SECRET_ACCESS_KEY: ZHVtbXk=
  KAFKA_BROKERS: a2Fma2Etc2VydmljZTo5MDky
  KAFKA_TOPIC: Y2hhbGxhbg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challan-data-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challan-data-svc
  template:
    metadata:
      labels:
        app: challan-data-svc
    spec:
      containers:
        - name: challan-data-svc
          image: challan-data-svc:v1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: challan-data-svc-secret
---
apiVersion: v1
kind: Service
metadata:
  name: challan-data-svc
  labels:
    app: challan-data-svc
spec:
  type: NodePort
  ports:
    - nodePort: 30090
      port: 8081
      targetPort: 8081
  selector:
    app: challan-data-svc