apiVersion: v1
kind: PersistentVolume
metadata:
  name: dynamodb-volume
  labels:
    type: local
    app: dynamodb
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/dynamodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-volume-claim
  labels:
    app: dynamodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: 'amazon/dynamodb-local:latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/dynamodb/data
              name: dynamodbdata
      volumes:
        - name: dynamodbdata
          persistentVolumeClaim:
            claimName: dynamodb-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  labels:
    app: dynamodb
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: dynamodb